name: Validações de pr

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  verificar_tag_existente:
    name: Verificar tag existente
    runs-on: ubuntu-22.04
    environment: production
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Coleta a tag que será criada
        id: coleta_tag
        run: |
          TAG_VERSION="$(cat VERSION)"
          if [ -z "$TAG_VERSION" ]; then
            echo "A tag não pode ser vazia"
            exit 1
          fi
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Exibe a tag que será criada
        run: echo "${{ steps.coleta_tag.outputs.TAG_VERSION }}"

      - name: Verifica se a tag já existe
        run: |
          TAG="$(git tag | grep -F "${{ steps.coleta_tag.outputs.TAG_VERSION }}" || true)"
          if [ -z "$TAG" ]; then
            exit 0
          else
            echo "A versão ${{ steps.coleta_tag.outputs.TAG_VERSION }} já existe"
            exit 1
          fi